# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: rust:1.31.0

before_script:
  - cargo version
  - rustup component add rustfmt

stages:
  - build
  - tests
  - examples
  - format

build:
  stage: build
  script:
    - cargo build

unit-tests:
  stage: tests
  script:
    - cargo test --lib

integration-tests:
  stage: tests
  script:
    - cargo test --test generative_tests --features "integration_test"

build-doc:
  stage: tests
  script:
    - cargo doc

serde:
  stage: examples
  script:
    - cargo run --example serde

ternary:
  stage: examples
  script:
    - cargo run --example ternary

fmt:
  stage: format
  script:
      # When running with --check, Rustfmt will exit with 0 if Rustfmt would
      # not make any formatting changes to the input, and 1 if Rustfmt would
      # make changes.
    - cargo fmt --all -- --check
