[package]
name = "casper"
version = "0.0.0"
authors = ["pZ4 <pz4@getnada.com>"]

[dependencies]
rayon = "*"
digest = "0.7"
proptest = "0.6.0"
rand = "*"

[dev-dependencies]
quickcheck = "*"
serde = "1.0.79"
serde_derive = "1.0.79"
bincode = "1.0.1"
blake2 = "0.7"
itertools = "0.7.8"
