[package]
name = "casper"
version = "0.0.0"
authors = ["pZ4 <pz4@protonmail.ch>"]

[dependencies]
rayon = "*"
digest = "0.7"
serde = "1.0.79"
serde_derive = "1.0.79"
bincode = "1.0.1"
blake2 = "0.7"
itertools = "0.7.8"
proptest = { version = "0.9.1", optional = true }
rand = { version = "0.6.5", optional = true }
flame = "0.2.2"
flamer = "0.3"

[features]
integration_test = ["proptest", "rand"]
